# Generated by Django 5.0.6 on 2025-03-23 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_garantia', models.DateField(blank=True, null=True)),
                ('fecha_expericion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('En mantenimiento', 'En mantenimiento'), ('Fuera de servicio', 'Fuera de servicio'), ('Descontinuado', 'Descontinuado')], default='Operativo', max_length=20)),
                ('categoria', models.ForeignKey(db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.categoria')),
                ('ubicacion', models.ForeignKey(db_column='ubicacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.ubicacion')),
            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Asignación', 'Asignación'), ('Cambio de ubicación', 'Cambio de ubicación'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, to='equipment.equipo')),
                ('nueva_ubicacion', models.ForeignKey(db_column='nueva_ubicacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.ubicacion')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
    ]
